CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), session_hash text NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE trips (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, name text NOT NULL, country text NOT NULL, city text NOT NULL, duration text NOT NULL, budget text NOT NULL, travelers text NOT NULL, style text NOT NULL, description text NOT NULL, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE travel_days (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), trip_id uuid NOT NULL REFERENCES trips(id) ON DELETE CASCADE, client_id text NOT NULL, day_number integer NOT NULL, title text NOT NULL, city text, region text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE travel_blocks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), day_id uuid NOT NULL REFERENCES travel_days(id) ON DELETE CASCADE, client_id text NOT NULL, position integer NOT NULL, data jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE travel_connections (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), day_id uuid NOT NULL REFERENCES travel_days(id) ON DELETE CASCADE, client_id text NOT NULL, data jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE travel_sources (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), trip_id uuid NOT NULL REFERENCES trips(id) ON DELETE CASCADE, type text NOT NULL, content_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE ai_generation_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), trip_id uuid REFERENCES trips(id) ON DELETE CASCADE, provider text NOT NULL, model text NOT NULL, status text NOT NULL, input_tokens integer, output_tokens integer, error_code text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX trips_user_id_idx ON trips(user_id); CREATE INDEX travel_days_trip_id_idx ON travel_days(trip_id); CREATE INDEX travel_blocks_day_id_idx ON travel_blocks(day_id); CREATE INDEX travel_connections_day_id_idx ON travel_connections(day_id);
