import { API_TIMEOUT_MS,INTERNAL_ANALYSIS_ENDPOINT,INTERNAL_SOURCE_ANALYSIS_ENDPOINT,INTERNAL_GENERATE_TRIP_ENDPOINT,INTERNAL_RECOMMENDATIONS_ENDPOINT,INTERNAL_TRIPS_ENDPOINT } from './config';
import type { TravelPlanPayload } from '@travel-blocks/shared';
import type { SavedTravelPlan,TravelAnalysisInput,TravelBlock,TravelDay,TripFormData } from '../types/travel';
async function request<T>(url:string,init?:RequestInit):Promise<T>{const controller=new AbortController();const timer=window.setTimeout(()=>controller.abort(),API_TIMEOUT_MS);try{const response=await fetch(url,{...init,credentials:'same-origin',signal:controller.signal,headers:{'Content-Type':'application/json',...init?.headers}});if(!response.ok){const body=await response.json().catch(()=>null) as {error?:{message?:string;retryable?:boolean}}|null;throw new Error(body?.error?.message||'API 요청에 실패했습니다.');}return response.status===204?undefined as T:response.json() as Promise<T>;}catch(error){if(error instanceof DOMException&&error.name==='AbortError')throw new Error('API 요청 시간이 초과되었습니다. 다시 시도해 주세요.');throw error;}finally{window.clearTimeout(timer)}}
export const createTripFromForm=async(input:TripFormData):Promise<TravelPlanPayload>=>({trip:{...input},days:[{id:'day-'+Date.now(),dayNumber:1,title:'Day 1',city:input.city||undefined,region:input.city||undefined,blocks:[]}],connections:[]});
export const generateTripWithAI=(prompt:string)=>request<TravelPlanPayload>(INTERNAL_GENERATE_TRIP_ENDPOINT,{method:'POST',body:JSON.stringify({prompt})});
export const analyzeLinkOrText=(input:TravelAnalysisInput)=>request<{days:TravelDay[]} | TravelPlanPayload>(INTERNAL_ANALYSIS_ENDPOINT,{method:'POST',body:JSON.stringify({content:input.content})}).then((x)=>x.days);
export async function createTripFromSource(content:string):Promise<TravelPlanPayload>{const result=await request<TravelPlanPayload>(INTERNAL_SOURCE_ANALYSIS_ENDPOINT,{method:'POST',body:JSON.stringify({input:content})});return result;}
export const getRecommendations=(trip?:TripFormData,day?:TravelDay)=>request<TravelBlock[]>(INTERNAL_RECOMMENDATIONS_ENDPOINT,{method:'POST',body:JSON.stringify({trip,day,existingPlaces:day?.blocks??[]})});
export const createSavedTrip=(payload:TravelPlanPayload)=>request<SavedTravelPlan>(INTERNAL_TRIPS_ENDPOINT,{method:'POST',body:JSON.stringify(payload)});
export const updateSavedTrip=(id:string,version:number,payload:TravelPlanPayload)=>request<SavedTravelPlan>(`${INTERNAL_TRIPS_ENDPOINT}/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({...payload,version})});
export const loadTrips=()=>request<SavedTravelPlan[]>(INTERNAL_TRIPS_ENDPOINT);
export const loadTrip=(id:string)=>request<SavedTravelPlan>(`${INTERNAL_TRIPS_ENDPOINT}/${encodeURIComponent(id)}`);
