import { describe, expect, it } from 'vitest';
import { checkOpeningHoursFeasibility, type PlaceOpeningHoursSnapshot } from '../src/openingHoursFeasibility.js';
import type { TravelPlanDraft } from '@travel-blocks/shared';
const fact = (periods: PlaceOpeningHoursSnapshot['regularHours']['periods']): PlaceOpeningHoursSnapshot => ({ provider: 'test', providerPlaceId: 'p1', source: 'test', retrievedAt: '2026-01-01T00:00:00Z', timeZone: 'Asia/Seoul', regularHours: { periods }, dataQualityFlags: [] });
const plan = (time = '10:00'): TravelPlanDraft => ({ trip: { name: 'x', country: 'x', city: 'x', duration: '1 day', budget: '', travelers: '', style: '', description: '' }, days: [{ id: 'd1', dayNumber: 1, title: 'Day 1', city: 'x', blocks: [{ id: 'b1', title: 'x', category: 'sightseeing', priceLevel: 'low', location: 'x', time, place: { provider: 'test', providerPlaceId: 'p1', verified: true } }] }], connections: [] });
describe('opening hours feasibility', () => {
  it('handles regular hours and closed times', () => { const hours = fact([{ openDay: 1, openTime: '09:00', closeDay: 1, closeTime: '18:00' }]); expect(checkOpeningHoursFeasibility(plan(), { 'test:p1': hours }, { tripStartDate: '2026-10-12' }).summary.caution).toBe(1); expect(checkOpeningHoursFeasibility(plan('20:00'), { 'test:p1': hours }, { tripStartDate: '2026-10-12' }).summary.infeasible).toBe(1); });
  it('handles overnight and 24 hour periods', () => { const overnight = fact([{ openDay: 5, openTime: '22:00', closeDay: 6, closeTime: '02:00' }]); const saturday = { ...plan('01:00'), days: [{ ...plan('01:00').days[0], dayNumber: 6 }] }; expect(checkOpeningHoursFeasibility(saturday, { 'test:p1': overnight }, { tripStartDate: '2026-10-12' }).summary.caution).toBe(1); const allDay = fact([{ openDay: 1, openTime: '00:00' }]); expect(checkOpeningHoursFeasibility(plan(), { 'test:p1': allDay }, { tripStartDate: '2026-10-12' }).summary.caution).toBe(1); });
  it('returns unknown when facts, date, or time are unavailable', () => { expect(checkOpeningHoursFeasibility(plan(), {}, { tripStartDate: '2026-10-12' }).summary.unknown).toBe(1); expect(checkOpeningHoursFeasibility(plan('오전'), { 'test:p1': fact([{ openDay: 1, openTime: '09:00', closeDay: 1, closeTime: '18:00' }]) }).summary.unknown).toBe(1); });
});
