import { randomUUID } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { TestAiProvider, TestPlaceProvider, fixturePlan } from '@travel-blocks/test-fixtures';
import { AnonymousSessionAuth } from '../src/auth.js';
import { buildApp } from '../src/app.js';
import type { TripRepository } from '../src/repository.js';
import type { SavedTravelPlan, TravelPlanPayload } from '@travel-blocks/shared';
class Repo implements TripRepository { users=new Map<string,string>(); trips=new Map<string,SavedTravelPlan>(); async findOrCreateUser(h:string){if(!this.users.has(h))this.users.set(h,randomUUID());return this.users.get(h)!} async create(userId:string,p:TravelPlanPayload){const now=new Date().toISOString();const v={id:randomUUID(),title:p.trip.name,subtitle:'',...structuredClone(p),version:1,createdAt:now,updatedAt:now,userId} as SavedTravelPlan&{userId:string};this.trips.set(v.id,v);return v} async list(u:string){return [...this.trips.values()].filter((x:any)=>x.userId===u)} async get(u:string,id:string){const x=this.trips.get(id) as any;return x?.userId===u?x:null} async update(u:string,id:string,p:TravelPlanPayload,version:number){const old=await this.get(u,id);if(!old)return null;if(old.version!==version)return 'conflict';const next={...old,...structuredClone(p),title:p.trip.name,version:version+1,updatedAt:new Date().toISOString()};this.trips.set(id,next);return next} async delete(u:string,id:string){if(!await this.get(u,id))return false;this.trips.delete(id);return true} }
const cookie=(res:any)=>String(res.headers['set-cookie']).split(';')[0];
describe('Trip API',()=>{it('생성, 같은 ID 수정, 삭제를 수행한다',async()=>{const repo=new Repo();const app=await buildApp({repository:repo,auth:new AnonymousSessionAuth(repo),ai:new TestAiProvider(),places:new TestPlaceProvider()});const created=await app.inject({method:'POST',url:'/api/v1/trips',payload:fixturePlan});expect(created.statusCode).toBe(201);const session=cookie(created);const first=created.json();const changed={...fixturePlan,trip:{...fixturePlan.trip,name:'수정 여행'},version:first.version};const updated=await app.inject({method:'PATCH',url:`/api/v1/trips/${first.id}`,headers:{cookie:session},payload:changed});expect(updated.json()).toMatchObject({id:first.id,title:'수정 여행',version:2});expect(repo.trips.size).toBe(1);expect((await app.inject({method:'DELETE',url:`/api/v1/trips/${first.id}`,headers:{cookie:session}})).statusCode).toBe(204);await app.close();});
it('다른 익명 사용자의 trip 접근을 차단한다',async()=>{const repo=new Repo();const app=await buildApp({repository:repo,auth:new AnonymousSessionAuth(repo),ai:new TestAiProvider(),places:new TestPlaceProvider()});const created=await app.inject({method:'POST',url:'/api/v1/trips',payload:fixturePlan});expect((await app.inject({method:'GET',url:`/api/v1/trips/${created.json().id}`})).statusCode).toBe(404);await app.close();});
it('AI 추천은 검증 및 중복 제거된 장소만 반환한다',async()=>{const repo=new Repo();const app=await buildApp({repository:repo,auth:new AnonymousSessionAuth(repo),ai:new TestAiProvider(),places:new TestPlaceProvider()});const r=await app.inject({method:'POST',url:'/api/v1/ai/recommendations',payload:{trip:fixturePlan.trip,day:fixturePlan.days[0],existingPlaces:[]}});expect(r.json()).toHaveLength(3);expect(r.json()[0].place.verified).toBe(true);await app.close();});});
